# Generated by Django 4.0.5 on 2022-06-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.TextField()),
                ('nombreProfesor', models.TextField()),
                ('categoria', models.TextField()),
                ('duracion', models.TextField()),
                ('fechaPublicacion', models.DateTimeField()),
            ],
        ),
    ]
