# Generated by Django 4.0.5 on 2022-06-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.TextField(max_length=50)),
                ('nombreProfesor', models.TextField(max_length=50)),
                ('totalLecciones', models.TextField(max_length=10)),
                ('totalHoras', models.TextField(max_length=15)),
                ('clasificacionCurso', models.TextField(max_length=20)),
                ('fechaPublicacion', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
